# Generated by Django 3.2.15 on 2022-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='ashutoshpawar', max_length=100),
            preserve_default=False,
        ),
    ]
